// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StarFleetBattles.Data;

#nullable disable

namespace StarFleetBattles.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StarFleetBattles.Models.EnergyAllocationForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivateShields")
                        .HasColumnType("int");

                    b.Property<int>("ActiveFireControl")
                        .HasColumnType("int");

                    b.Property<int>("BatteryCapacityDischarged")
                        .HasColumnType("int");

                    b.Property<int>("BatteryPowerAvaiable")
                        .HasColumnType("int");

                    b.Property<int>("BatteryPowerUsed")
                        .HasColumnType("int");

                    b.Property<int>("ChargePhaserCapacitors")
                        .HasColumnType("int");

                    b.Property<int>("ChargeWW_SS")
                        .HasColumnType("int");

                    b.Property<int>("CloakingDevice")
                        .HasColumnType("int");

                    b.Property<int>("DamageControl")
                        .HasColumnType("int");

                    b.Property<int>("ECCM")
                        .HasColumnType("int");

                    b.Property<int>("ECM")
                        .HasColumnType("int");

                    b.Property<int>("EM_Braking")
                        .HasColumnType("int");

                    b.Property<int>("EnergyForMovement")
                        .HasColumnType("int");

                    b.Property<int>("GeneralReinforcement")
                        .HasColumnType("int");

                    b.Property<int>("HET")
                        .HasColumnType("int");

                    b.Property<int>("HeavyWeaponsA")
                        .HasColumnType("int");

                    b.Property<int>("HeavyWeaponsB")
                        .HasColumnType("int");

                    b.Property<int>("HeavyWeaponsC")
                        .HasColumnType("int");

                    b.Property<int>("HeavyWeaponsD")
                        .HasColumnType("int");

                    b.Property<int>("HeavyWeaponsE")
                        .HasColumnType("int");

                    b.Property<int>("HeavyWeaponsF")
                        .HasColumnType("int");

                    b.Property<int>("HeavyWeaponsG")
                        .HasColumnType("int");

                    b.Property<int>("HeavyWeaponsH")
                        .HasColumnType("int");

                    b.Property<int>("ImpulseEnginePower")
                        .HasColumnType("int");

                    b.Property<int>("Labs")
                        .HasColumnType("int");

                    b.Property<int>("LifeSupport")
                        .HasColumnType("int");

                    b.Property<string>("MovementPlot_Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhaserCapacitorsCharged")
                        .HasColumnType("int");

                    b.Property<int>("PhaserCapacitorsUsed")
                        .HasColumnType("int");

                    b.Property<string>("Player")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PowerUsed")
                        .HasColumnType("int");

                    b.Property<int>("ReactorPower")
                        .HasColumnType("int");

                    b.Property<int>("RechargeBatteries_ReserveWarp")
                        .HasColumnType("int");

                    b.Property<int>("SpecificReinforcement_1")
                        .HasColumnType("int");

                    b.Property<int>("SpecificReinforcement_2")
                        .HasColumnType("int");

                    b.Property<int>("SpecificReinforcement_3")
                        .HasColumnType("int");

                    b.Property<int>("SpecificReinforcement_4")
                        .HasColumnType("int");

                    b.Property<int>("SpecificReinforcement_5")
                        .HasColumnType("int");

                    b.Property<int>("SpecificReinforcement_6")
                        .HasColumnType("int");

                    b.Property<int>("TotalPowerAvailable")
                        .HasColumnType("int");

                    b.Property<int>("Tractor_NegativeTractor")
                        .HasColumnType("int");

                    b.Property<int>("Transporters")
                        .HasColumnType("int");

                    b.Property<int>("WarpEnginePower")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EnergyAllocationForms");
                });
#pragma warning restore 612, 618
        }
    }
}
